#!/bin/sh
# Gradle wrapper shell script (standard — generated by gradle wrapper)
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
DIRNAME=$(dirname "$0")
cd "$DIRNAME" >/dev/null
APP_HOME=$(pwd -P)
cd - >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

JAVA_EXE=$(which java 2>/dev/null) || { echo "ERROR: JAVA_HOME is not set and 'java' not in PATH." >&2; exit 1; }

exec "$JAVA_EXE" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  "-Dorg.gradle.appname=$APP_BASE_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
